### ISSUE TITLE
Y-axis issue on Intensity v Distance plot

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-eventpages#1720]
I believe this was a problem at one point in the past?

- https://earthquake.usgs.gov/earthquakes/eventpage/se60233907/dyfi/intensity-vs-distance
- https://earthquake.usgs.gov/earthquakes/eventpage/uu60315157/dyfi/intensity-vs-distance
- https://earthquake.usgs.gov/earthquakes/eventpage/us1000jb8d/dyfi/intensity-vs-distance

That last one has no plot at all?

**Comment by dslosky-usgs** [comment]
@ehunter-usgs I noticed some weird y-axis behavior with the shakemap plots I've been working on and the issue seen in those first two links should be resolved with the incoming update. That third link is a little weird... There's only one response, which is an edge case we test for (I'm pretty sure), but haven't ever visually confirmed... looks like it needs some work, thanks for pointing it out!

**Comment by vinceq-usgs** [comment]
Is there any progress on this? This is still happening on all the live DYFI events.

**Comment by vinceq-usgs** [comment]
Some more testing.... resizing the browser window can create multiples of the Y axis ticks, up to 5 ticks (e. g. 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 ....) However, looking at the values of the plotted points, it seems that the graph is attempting to plot decimal intensities (2.0 2.2 2.4 2.6. 2.8...) but rendering them as integers (2 2 2 2 2...)?

**Comment by dslosky-usgs** [comment]
Hey @vinceq-usgs, the fix for this is encompassed in #1735! Just waiting for the HazDev team to get some time to checkout and merge the PR
